version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      # - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=8000 --reload
    depends_on:
      - selenium
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - app_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - backend
    networks:
      - app-network

  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - app-network

volumes:
  app_node_modules:


networks:
  app-network:
    driver: bridge
